#!/bin/bash

echo "🔐 EVEP Authentication Clear Script"
echo "=================================="
echo ""
echo "This script will help you clear authentication data from your browser."
echo ""
echo "📋 Instructions:"
echo "1. Open your browser and go to: http://localhost:3013"
echo "2. Open Developer Tools (F12 or right-click → Inspect)"
echo "3. Go to the Console tab"
echo "4. Run this command:"
echo ""
echo "   localStorage.clear()"
echo ""
echo "5. Refresh the page (F5 or Ctrl+R)"
echo ""
echo "🎯 Alternative method:"
echo "You can also manually clear these specific items:"
echo "   localStorage.removeItem('evep_token')"
echo "   localStorage.removeItem('evep_user')"
echo ""
echo "✅ After clearing, you should see the login page instead of the dashboard."
echo ""
echo "🔗 Login URLs:"
echo "   Frontend: http://localhost:3013"
echo "   API Docs: http://localhost:8013/docs"
echo ""
echo "👤 Demo Accounts:"
echo "   Doctor: doctor@evep.com / demo123"
echo "   Teacher: teacher@evep.com / demo123"
echo "   Parent: parent@evep.com / demo123"
echo "   Admin: admin@evep.com / demo123"
