import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

// Translation data
const translations = {
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.hide_filters': 'Hide Filters',
    'common.reset': 'Reset',
    'common.print': 'Print',
    'common.refresh': 'Refresh',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.submit': 'Submit',
    'common.clear': 'Clear',
    'common.all': 'All',
    'common.none': 'None',
    'common.select': 'Select',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.actions': 'Actions',
    'common.created_at': 'Created At',
    'common.updated_at': 'Updated At',
    'common.total': 'Total',
    'common.completed': 'Completed',
    'common.pending': 'Pending',
    'common.in_progress': 'In Progress',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.public': 'Public',
    'common.private': 'Private',
    'common.draft': 'Draft',
    'common.published': 'Published',
    'common.archived': 'Archived',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.school_management': 'School Management',
    'nav.school_screenings': 'School Screenings',
    'nav.students': 'Students',
    'nav.teachers': 'Teachers',
    'nav.schools': 'Schools',
    'nav.parents': 'Parents',
    'nav.medical_staff': 'Medical Staff',
    'nav.hospitals': 'Hospitals',
    'nav.screenings': 'Screenings',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.user_management': 'User Management',
    'nav.admin_panel': 'Admin Panel',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    'nav.notifications': 'Notifications',
    'nav.language': 'Language',
    
    // School Screenings
    'school_screenings.title': 'School Screenings',
    'school_screenings.subtitle': 'Manage school-based vision screening sessions',
    'school_screenings.create_new': 'Create New School Screening',
    'school_screenings.total_screenings': 'Total Screenings',
    'school_screenings.completed': 'Completed',
    'school_screenings.in_progress': 'In Progress',
    'school_screenings.pending': 'Pending',
    'school_screenings.available_students': 'Available Students',
    'school_screenings.recent_screenings': 'Recent School Screenings',
    'school_screenings.show_filters': 'Show Filters',
    'school_screenings.student': 'Student',
    'school_screenings.examiner': 'Examiner',
    'school_screenings.type': 'Type',
    'school_screenings.status': 'Status',
    'school_screenings.date': 'Date',
    'school_screenings.actions': 'Actions',
    'school_screenings.screenings': 'screenings',
    'school_screenings.rescreen': 'Re-screen',
    'school_screenings.history': 'History',
    'school_screenings.view_details': 'View Details',
    'school_screenings.edit_screening': 'Edit Screening',
    'school_screenings.delete_screening': 'Delete Screening',
    'school_screenings.print_screening': 'Print Screening',
    'school_screenings.view_history': 'View Student History',
    'school_screenings.basic_school': 'Basic School Screening',
    'school_screenings.vision_test': 'Vision Test',
    'school_screenings.comprehensive_vision': 'Comprehensive Vision Test',
    'school_screenings.color_blindness': 'Color Blindness Test',
    'school_screenings.depth_perception': 'Depth Perception Test',
    
    // Screening Form
    'screening_form.title': 'Create New School Screening',
    'screening_form.student_selection': 'Student Selection',
    'screening_form.screening_setup': 'Screening Setup',
    'screening_form.screening_results': 'Screening Results',
    'screening_form.conclusion': 'Conclusion',
    'screening_form.select_student': 'Select Student',
    'screening_form.select_examiner': 'Select Examiner',
    'screening_form.screening_type': 'Screening Type',
    'screening_form.screening_date': 'Screening Date',
    'screening_form.notes': 'Notes',
    'screening_form.left_eye': 'Left Eye',
    'screening_form.right_eye': 'Right Eye',
    'screening_form.distance_acuity': 'Distance Acuity',
    'screening_form.near_acuity': 'Near Acuity',
    'screening_form.color_vision': 'Color Vision',
    'screening_form.depth_perception': 'Depth Perception',
    'screening_form.conclusion_text': 'Conclusion',
    'screening_form.recommendations': 'Recommendations',
    'screening_form.referral_needed': 'Referral Needed',
    'screening_form.referral_notes': 'Referral Notes',
    
    // Student Information
    'student.name': 'Student Name',
    'student.grade_level': 'Grade Level',
    'student.school': 'School',
    'student.birth_date': 'Birth Date',
    'student.age': 'Age',
    'student.gender': 'Gender',
    'student.parent_name': 'Parent Name',
    'student.parent_phone': 'Parent Phone',
    'student.address': 'Address',
    'student.male': 'Male',
    'student.female': 'Female',
    'student.years': 'years',
    
    // Teacher Information
    'teacher.name': 'Teacher Name',
    'teacher.school': 'School',
    'teacher.email': 'Email',
    'teacher.phone': 'Phone',
    
    // Messages
    'message.screening_created': 'Screening created successfully',
    'message.screening_updated': 'Screening updated successfully',
    'message.screening_deleted': 'Screening deleted successfully',
    'message.rescreen_created': 'Re-screen created successfully',
    'message.error_creating_screening': 'Error creating screening',
    'message.error_updating_screening': 'Error updating screening',
    'message.error_deleting_screening': 'Error deleting screening',
    'message.error_fetching_data': 'Error fetching data',
    'message.confirm_delete': 'Are you sure you want to delete this screening?',
    'message.confirm_rescreen': 'Are you sure you want to create a re-screen for this student?',
    'message.duplicate_screening': 'Student already has a screening on this date. Use re-screen action instead.',
    'message.print_dialog_opened': 'Print dialog opened successfully',
    'message.popup_blocked': 'Please allow popups to print the screening record',
    
    // Print Report
    'print.title': 'Vision Screening Report',
    'print.student_info': 'Student Information',
    'print.examiner_info': 'Examiner Information',
    'print.screening_results': 'Screening Results',
    'print.conclusion_recommendations': 'Conclusion & Recommendations',
    'print.generated_by': 'This report was generated by EVEP System',
    'print.printed_on': 'Printed on',
    'print.eye_left': 'Left',
    'print.eye_right': 'Right',
    'print.referral_yes': 'Yes',
    'print.referral_no': 'No',
    
    // Breadcrumbs
    'breadcrumb.dashboard': 'Dashboard',
    'breadcrumb.school_management': 'School Management',
    'breadcrumb.school_screenings': 'School Screenings',
    
    // Filter Labels
    'filter.status': 'Status',
    'filter.type': 'Type',
    'filter.student': 'Student',
    'filter.examiner': 'Examiner',
    'filter.date_from': 'Date From',
    'filter.date_to': 'Date To',
    'filter.all_status': 'All Status',
    'filter.all_type': 'All Type',
    
    // Dialog Titles
    'dialog.create_screening': 'Create New School Screening',
    'dialog.edit_screening': 'Edit School Screening',
    'dialog.view_screening': 'View Screening Details',
    'dialog.student_history': 'Student Screening History',
    'dialog.confirm_delete': 'Confirm Delete',
    'dialog.confirm_rescreen': 'Confirm Re-screen',
    
    // Form Steps
    'step.student_selection': 'Student Selection',
    'step.screening_setup': 'Screening Setup',
    'step.screening_results': 'Screening Results',
    'step.conclusion': 'Conclusion',
    
    // Form Labels
    'form.select_student': 'Select Student',
    'form.select_examiner': 'Select Examiner',
    'form.screening_type': 'Screening Type',
    'form.screening_date': 'Screening Date',
    'form.notes': 'Notes',
    'form.left_eye': 'Left Eye',
    'form.right_eye': 'Right Eye',
    'form.distance_acuity': 'Distance Acuity',
    'form.near_acuity': 'Near Acuity',
    'form.color_vision': 'Color Vision',
    'form.depth_perception': 'Depth Perception',
    'form.conclusion': 'Conclusion',
    'form.recommendations': 'Recommendations',
    'form.referral_needed': 'Referral Needed',
    'form.referral_notes': 'Referral Notes',
    
    // Action Buttons
    'action.view': 'View',
    'action.edit': 'Edit',
    'action.delete': 'Delete',
    'action.print': 'Print',
    'action.rescreen': 'Re-screen',
    'action.history': 'History',
    'action.save': 'Save',
    'action.cancel': 'Cancel',
    'action.close': 'Close',
    'action.next': 'Next',
    'action.previous': 'Previous',
    'action.finish': 'Finish',
    
    // Status Messages
    'status.loading': 'Loading...',
    'status.success': 'Success',
    'status.error': 'Error',
    'status.warning': 'Warning',
    'status.info': 'Information',
    
    // Validation Messages
    'validation.required': 'This field is required',
    'validation.invalid_email': 'Please enter a valid email address',
    'validation.invalid_phone': 'Please enter a valid phone number',
    'validation.invalid_date': 'Please enter a valid date',
    'validation.min_length': 'Minimum length is {{min}} characters',
    'validation.max_length': 'Maximum length is {{max}} characters',
    'validation.email_required': 'Email is required',
    'validation.email_invalid': 'Please enter a valid email address',
    'validation.password_required': 'Password is required',
    'validation.password_min_length': 'Password must be at least 6 characters',
    
    // Time and Date
    'time.today': 'Today',
    'time.yesterday': 'Yesterday',
    'time.tomorrow': 'Tomorrow',
    'time.now': 'Now',
    'time.ago': 'ago',
    'time.in': 'in',
    
    // Pagination
    'pagination.page': 'Page',
    'pagination.of': 'of',
    'pagination.rows_per_page': 'Rows per page',
    'pagination.showing': 'Showing',
    'pagination.to': 'to',
    'pagination.of_total': 'of {{total}}',
    
    // Search and Sort
    'search.placeholder': 'Search...',
    'search.no_results': 'No results found',
    'search.clear': 'Clear search',
    'sort.asc': 'Sort ascending',
    'sort.desc': 'Sort descending',
    'sort.by': 'Sort by',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Medical Portal Overview',
    'dashboard.total_patients': 'Total Patients',
    'dashboard.total_screenings': 'Total Screenings',
    'dashboard.pending_screenings': 'Pending Screenings',
    'dashboard.completed_screenings': 'Completed Screenings',
    'dashboard.today_appointments': 'Today\'s Appointments',
    'dashboard.recent_activities': 'Recent Activities',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.statistics': 'Statistics',
    'dashboard.overview': 'Overview',
    
    // Patients
    'patients.title': 'Patients',
    'patients.subtitle': 'Patient Management',
    'patients.add_patient': 'Add Patient',
    'patients.search_patients': 'Search Patients',
    'patients.filter_by_status': 'Filter by Status',
    'patients.filter_by_gender': 'Filter by Gender',
    'patients.all_status': 'All Status',
    'patients.all_gender': 'All Gender',
    'patients.active': 'Active',
    'patients.inactive': 'Inactive',
    'patients.male': 'Male',
    'patients.female': 'Female',
    'patients.patient_details': 'Patient Details',
    'patients.edit_patient': 'Edit Patient',
    'patients.delete_patient': 'Delete Patient',
    'patients.view_patient': 'View Patient',
    'patients.patient_id': 'Patient ID',
    'patients.full_name': 'Full Name',
    'patients.date_of_birth': 'Date of Birth',
    'patients.gender': 'Gender',
    'patients.phone': 'Phone',
    'patients.email': 'Email',
    'patients.address': 'Address',
    'patients.emergency_contact': 'Emergency Contact',
    'patients.medical_history': 'Medical History',
    'patients.insurance_info': 'Insurance Information',
    'patients.appointment': 'Appointment Patients',
    'patients.manual_registration': 'Manual Registration',
    
    // Screenings
    'screenings.title': 'Screenings',
    'screenings.subtitle': 'Vision Screening Management',
    'screenings.create_session': 'Create Screening Session',
    'screenings.active_sessions': 'Active Sessions',
    'screenings.completed_sessions': 'Completed Sessions',
    'screenings.screening_type': 'Screening Type',
    'screenings.basic_screening': 'Basic Screening',
    'screenings.comprehensive_screening': 'Comprehensive Screening',
    'screenings.mobile_screening': 'Mobile Screening',
    'screenings.standard_screening': 'Standard Screening',
    'screenings.session_details': 'Session Details',
    'screenings.start_screening': 'Start Screening',
    'screenings.complete_screening': 'Complete Screening',
    'screenings.screening_results': 'Screening Results',
    'screenings.left_eye': 'Left Eye',
    'screenings.right_eye': 'Right Eye',
    'screenings.distance_vision': 'Distance Vision',
    'screenings.near_vision': 'Near Vision',
    'screenings.color_vision': 'Color Vision',
    'screenings.depth_perception': 'Depth Perception',
    'screenings.notes': 'Notes',
    'screenings.recommendations': 'Recommendations',
    'screenings.follow_up_required': 'Follow-up Required',
    'screenings.all_screenings': 'All Screenings',
    
    // Reports
    'reports.title': 'Reports',
    'reports.subtitle': 'Medical Reports & Analytics',
    'reports.generate_report': 'Generate Report',
    'reports.screening_reports': 'Screening Reports',
    'reports.patient_reports': 'Patient Reports',
    'reports.statistical_reports': 'Statistical Reports',
    'reports.date_range': 'Date Range',
    'reports.from_date': 'From Date',
    'reports.to_date': 'To Date',
    'reports.report_type': 'Report Type',
    'reports.export_format': 'Export Format',
    'reports.pdf': 'PDF',
    'reports.excel': 'Excel',
    'reports.csv': 'CSV',
    'reports.download_report': 'Download Report',
    'reports.view_report': 'View Report',
    'reports.medical_reports': 'Medical Reports',
    'reports.evep_medical_panel': 'EVEP Medical Professional Panel',
    
    // EVEP Students
    'evep_students.title': 'EVEP Students',
    'evep_students.subtitle': 'Student Management',
    'evep_students.add_student': 'Add Student',
    'evep_students.student_code': 'Student Code',
    'evep_students.school_name': 'School Name',
    'evep_students.grade_level': 'Grade Level',
    'evep_students.grade_number': 'Grade Number',
    'evep_students.parent_name': 'Parent Name',
    'evep_students.consent_status': 'Consent Status',
    'evep_students.consent_given': 'Consent Given',
    'evep_students.consent_pending': 'Consent Pending',
    'evep_students.consent_denied': 'Consent Denied',
    'evep_students.filter_by_school': 'Filter by School',
    'evep_students.filter_by_grade': 'Filter by Grade',
    'evep_students.filter_by_consent': 'Filter by Consent',
    'evep_students.all_schools': 'All Schools',
    'evep_students.all_grades': 'All Grades',
    'evep_students.all_consent': 'All Consent Status',
    'evep_students.total_students': 'Total Students',
    'evep_students.male_students': 'Male Students',
    'evep_students.female_students': 'Female Students',
    'evep_students.students_list': 'Students List',
    
    // EVEP Parents
    'evep_parents.title': 'EVEP Parents',
    'evep_parents.subtitle': 'Parent Management',
    'evep_parents.add_parent': 'Add Parent',
    'evep_parents.parent_id': 'Parent ID',
    'evep_parents.relationship': 'Relationship',
    'evep_parents.father': 'Father',
    'evep_parents.mother': 'Mother',
    'evep_parents.guardian': 'Guardian',
    'evep_parents.occupation': 'Occupation',
    'evep_parents.workplace': 'Workplace',
    'evep_parents.children': 'Children',
    'evep_parents.emergency_contact': 'Emergency Contact',
    'evep_parents.total_parents': 'Total Parents',
    'evep_parents.parents_list': 'Parents List',
    
    // EVEP Teachers
    'evep_teachers.title': 'EVEP Teachers',
    'evep_teachers.subtitle': 'Teacher Management',
    'evep_teachers.add_teacher': 'Add Teacher',
    'evep_teachers.teacher_id': 'Teacher ID',
    'evep_teachers.position': 'Position',
    'evep_teachers.subject': 'Subject',
    'evep_teachers.experience_years': 'Experience (Years)',
    'evep_teachers.qualification': 'Qualification',
    'evep_teachers.classes': 'Classes',
    'evep_teachers.students_count': 'Students Count',
    'evep_teachers.total_teachers': 'Total Teachers',
    'evep_teachers.male_teachers': 'Male Teachers',
    'evep_teachers.female_teachers': 'Female Teachers',
    'evep_teachers.teachers_list': 'Teachers List',
    
    // EVEP Schools
    'evep_schools.title': 'EVEP Schools',
    'evep_schools.subtitle': 'School Management',
    'evep_schools.add_school': 'Add School',
    'evep_schools.school_id': 'School ID',
    'evep_schools.school_type': 'School Type',
    'evep_schools.public_school': 'Public School',
    'evep_schools.private_school': 'Private School',
    'evep_schools.school_level': 'School Level',
    'evep_schools.elementary': 'Elementary',
    'evep_schools.secondary': 'Secondary',
    'evep_schools.high_school': 'High School',
    'evep_schools.principal_name': 'Principal Name',
    'evep_schools.total_students': 'Total Students',
    'evep_schools.total_teachers': 'Total Teachers',
    'evep_schools.contact_person': 'Contact Person',
    'evep_schools.contact_phone': 'Contact Phone',
    'evep_schools.contact_email': 'Contact Email',
    
    // Admin Management
    'admin.title': 'Admin Panel',
    'admin.subtitle': 'System Administration',
    'admin.user_management': 'User Management',
    'admin.role_management': 'Role Management',
    'admin.permission_management': 'Permission Management',
    'admin.system_settings': 'System Settings',
    'admin.dashboard_title': 'Admin Dashboard',
    'admin.dashboard_subtitle': 'System overview and management',
    'admin.total_users': 'Total Users',
    'admin.total_patients': 'Total Patients',
    'admin.total_screenings': 'Total Screenings',
    'admin.security_settings': 'Security Settings',
    'admin.audit_logs': 'Audit Logs',
    'admin.system_monitoring': 'System Monitoring',
    'admin.backup_restore': 'Backup & Restore',
    'admin.database_management': 'Database Management',
    'admin.api_management': 'API Management',
    
    // User Management
    'user_management.title': 'User Management',
    'user_management.subtitle': 'Manage System Users',
    'user_management.add_user': 'Add User',
    'user_management.user_id': 'User ID',
    'user_management.username': 'Username',
    'user_management.full_name': 'Full Name',
    'user_management.role': 'Role',
    'user_management.department': 'Department',
    'user_management.status': 'Status',
    'user_management.last_login': 'Last Login',
    'user_management.created_at': 'Created At',
    'user_management.updated_at': 'Updated At',
    'user_management.active': 'Active',
    'user_management.inactive': 'Inactive',
    'user_management.suspended': 'Suspended',
    'user_management.reset_password': 'Reset Password',
    'user_management.change_role': 'Change Role',
    'user_management.activate_user': 'Activate User',
    'user_management.deactivate_user': 'Deactivate User',
    'user_management.total_users': 'Total Users',
    'user_management.active_users': 'Active Users',
    'user_management.inactive_users': 'Inactive Users',
    'user_management.search_users': 'Search users...',
    
    // RBAC Management
    'rbac.title': 'Role-Based Access Control',
    'rbac.subtitle': 'Manage Roles and Permissions',
    'rbac.create_role': 'Create Role',
    'rbac.edit_role': 'Edit Role',
    'rbac.delete_role': 'Delete Role',
    'rbac.role_name': 'Role Name',
    'rbac.role_description': 'Role Description',
    'rbac.permissions': 'Permissions',
    'rbac.roles': 'Roles',
    'rbac.user_roles': 'User Roles',
    'rbac.master_data': 'Master Data',
    'rbac.screening_rbac': 'Screening RBAC',
    'rbac.assign_permissions': 'Assign Permissions',
    'rbac.users_with_role': 'Users with this Role',
    'rbac.permission_categories': 'Permission Categories',
    'rbac.read': 'Read',
    'rbac.write': 'Write',
    'rbac.delete': 'Delete',
    'rbac.admin': 'Admin',
    'rbac.user': 'User',
    'rbac.guest': 'Guest',
    
    // Medical Staff
    'medical_staff.title': 'Medical Staff',
    'medical_staff.subtitle': 'Medical Personnel Management',
    'medical_staff.add_staff': 'Add Staff',
    'medical_staff.staff_id': 'Staff ID',
    'medical_staff.license_number': 'License Number',
    'medical_staff.specialization': 'Specialization',
    'medical_staff.experience': 'Experience',
    'medical_staff.certification': 'Certification',
    'medical_staff.availability': 'Availability',
    'medical_staff.schedule': 'Schedule',
    'medical_staff.patients_assigned': 'Patients Assigned',
    'medical_staff.screenings_performed': 'Screenings Performed',
    
    // Hospitals Management
    'hospitals.title': 'Hospitals',
    'hospitals.subtitle': 'Hospital Management',
    'hospitals.add_hospital': 'Add Hospital',
    'hospitals.hospital_id': 'Hospital ID',
    'hospitals.hospital_name': 'Hospital Name',
    'hospitals.hospital_type': 'Hospital Type',
    'hospitals.general_hospital': 'General Hospital',
    'hospitals.specialty_hospital': 'Specialty Hospital',
    'hospitals.clinic': 'Clinic',
    'hospitals.medical_center': 'Medical Center',
    'hospitals.capacity': 'Capacity',
    'hospitals.beds_available': 'Beds Available',
    'hospitals.emergency_services': 'Emergency Services',
    'hospitals.specialties': 'Specialties',
    'hospitals.contact_info': 'Contact Information',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'System Configuration',
    'settings.general_settings': 'General Settings',
    'settings.display_settings': 'Display Settings',
    'settings.notification_settings': 'Notification Settings',
    'settings.security_settings': 'Security Settings',
    'settings.medical_settings': 'Medical Settings',
    'settings.panel_name': 'Panel Name',
    'settings.panel_description': 'Panel Description',
    'settings.timezone': 'Timezone',
    'settings.date_format': 'Date Format',
    'settings.time_format': 'Time Format',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.light_theme': 'Light Theme',
    'settings.dark_theme': 'Dark Theme',
    'settings.auto_theme': 'Auto Theme',
    'settings.compact_mode': 'Compact Mode',
    'settings.show_animations': 'Show Animations',
    'settings.auto_refresh': 'Auto Refresh',
    'settings.refresh_interval': 'Refresh Interval',
    'settings.email_notifications': 'Email Notifications',
    'settings.push_notifications': 'Push Notifications',
    'settings.screening_alerts': 'Screening Alerts',
    'settings.appointment_reminders': 'Appointment Reminders',
    'settings.system_updates': 'System Updates',
    'settings.session_timeout': 'Session Timeout',
    'settings.require_password_change': 'Require Password Change',
    'settings.two_factor_auth': 'Two-Factor Authentication',
    'settings.audit_logging': 'Audit Logging',
    'settings.default_screening_type': 'Default Screening Type',
    'settings.auto_save_screening_data': 'Auto Save Screening Data',
    'settings.patient_data_retention': 'Patient Data Retention',
    'settings.medical_alerts': 'Medical Alerts',
    
    // AI Insights
    'ai_insights.title': 'AI Insights',
    'ai_insights.subtitle': 'Artificial Intelligence Analytics',
    'ai_insights.dashboard': 'AI Dashboard',
    'ai_insights.predictive_analytics': 'Predictive Analytics',
    'ai_insights.pattern_recognition': 'Pattern Recognition',
    'ai_insights.recommendations': 'AI Recommendations',
    'ai_insights.risk_assessment': 'Risk Assessment',
    'ai_insights.trend_analysis': 'Trend Analysis',
    'ai_insights.anomaly_detection': 'Anomaly Detection',
    'ai_insights.performance_metrics': 'Performance Metrics',
    'ai_insights.data_quality': 'Data Quality',
    'ai_insights.insights_generated': 'Insights Generated',
    'ai_insights.confidence_score': 'Confidence Score',
    'ai_insights.recommendation_engine': 'Recommendation Engine',
    'ai_insights.no_permission': 'You do not have permission to access AI Insights',
    
    // Authentication
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.forgot_password': 'Forgot Password',
    'auth.reset_password': 'Reset Password',
    'auth.change_password': 'Change Password',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.new_password': 'New Password',
    'auth.current_password': 'Current Password',
    'auth.remember_me': 'Remember Me',
    'auth.login_button': 'Sign In',
    'auth.register_button': 'Sign Up',
    'auth.login_title': 'Welcome Back',
    'auth.register_title': 'Create Account',
    'auth.login_subtitle': 'Sign in to your account',
    'auth.register_subtitle': 'Create a new account',
    'auth.switch_to_login': 'Already have an account? Sign in',
    'auth.switch_to_register': 'Don\'t have an account? Sign up',
    'auth.login_success': 'Login successful',
    'auth.login_error': 'Login failed',
    'auth.register_success': 'Registration successful',
    'auth.register_error': 'Registration failed',
    'auth.password_reset_sent': 'Password reset email sent',
    'auth.password_reset_error': 'Password reset failed',
    'auth.invalid_credentials': 'Invalid email or password',
    'auth.account_locked': 'Account is locked',
    'auth.account_disabled': 'Account is disabled',
    'auth.email_required': 'Email is required',
    'auth.password_required': 'Password is required',
    'auth.password_too_short': 'Password must be at least 8 characters',
    'auth.password_mismatch': 'Passwords do not match',
    'auth.email_invalid': 'Please enter a valid email address',
    'auth.sign_in': 'Sign In',
    'auth.access_dashboard': 'Access your medical professional dashboard',
    'auth.demo_access': 'Demo Access',
    'auth.demo_description': 'Try the platform with demo credentials',
    'auth.welcome_message': 'Welcome to EVEP Medical Professional Panel',
    'auth.demo_welcome': 'Welcome, {{role}}!',
    'auth.login_failed': 'Login failed',
    
    // Master Data Management
    'master_data.title': 'Master Data',
    'master_data.subtitle': 'System Master Data Management',
    'master_data.provinces': 'Provinces',
    'master_data.districts': 'Districts',
    'master_data.subdistricts': 'Subdistricts',
    'master_data.schools': 'Schools',
    'master_data.grades': 'Grades',
    'master_data.subjects': 'Subjects',
    'master_data.diseases': 'Diseases',
    'master_data.medications': 'Medications',
    'master_data.treatments': 'Treatments',
    'master_data.add_province': 'Add Province',
    'master_data.add_district': 'Add District',
    'master_data.add_subdistrict': 'Add Subdistrict',
    'master_data.add_school': 'Add School',
    'master_data.add_grade': 'Add Grade',
    'master_data.add_subject': 'Add Subject',
    'master_data.add_disease': 'Add Disease',
    'master_data.add_medication': 'Add Medication',
    'master_data.add_treatment': 'Add Treatment',
    
    // Geolocations Management
    'geolocations.title': 'Geolocations',
    'geolocations.subtitle': 'Geographic Location Management',
    'geolocations.latitude': 'Latitude',
    'geolocations.longitude': 'Longitude',
    'geolocations.address': 'Address',
    'geolocations.postal_code': 'Postal Code',
    'geolocations.map_view': 'Map View',
    'geolocations.location_details': 'Location Details',
    'geolocations.add_location': 'Add Location',
    'geolocations.edit_location': 'Edit Location',
    'geolocations.delete_location': 'Delete Location',
    'geolocations.search_location': 'Search Location',
    'geolocations.nearby_locations': 'Nearby Locations',
    'geolocations.distance': 'Distance',
    'geolocations.direction': 'Direction',
  },
  th: {
    // Common
    'common.loading': 'กำลังโหลด...',
    'common.error': 'ข้อผิดพลาด',
    'common.success': 'สำเร็จ',
    'common.cancel': 'ยกเลิก',
    'common.save': 'บันทึก',
    'common.delete': 'ลบ',
    'common.edit': 'แก้ไข',
    'common.view': 'ดู',
    'common.close': 'ปิด',
    'common.confirm': 'ยืนยัน',
    'common.yes': 'ใช่',
    'common.no': 'ไม่',
    'common.search': 'ค้นหา',
    'common.filter': 'กรอง',
    'common.hide_filters': 'ซ่อนตัวกรอง',
    'common.reset': 'รีเซ็ต',
    'common.print': 'พิมพ์',
    'common.refresh': 'รีเฟรช',
    'common.add': 'เพิ่ม',
    'common.remove': 'ลบออก',
    'common.back': 'กลับ',
    'common.next': 'ถัดไป',
    'common.previous': 'ก่อนหน้า',
    'common.submit': 'ส่ง',
    'common.clear': 'ล้าง',
    'common.all': 'ทั้งหมด',
    'common.none': 'ไม่มี',
    'common.select': 'เลือก',
    'common.required': 'จำเป็น',
    'common.optional': 'ไม่จำเป็น',
    'common.status': 'สถานะ',
    'common.date': 'วันที่',
    'common.time': 'เวลา',
    'common.name': 'ชื่อ',
    'common.email': 'อีเมล',
    'common.phone': 'โทรศัพท์',
    'common.address': 'ที่อยู่',
    'common.actions': 'การดำเนินการ',
    'common.created_at': 'สร้างเมื่อ',
    'common.updated_at': 'อัปเดตเมื่อ',
    'common.total': 'รวม',
    'common.completed': 'เสร็จสิ้น',
    'common.pending': 'รอดำเนินการ',
    'common.in_progress': 'กำลังดำเนินการ',
    'common.active': 'ใช้งาน',
    'common.inactive': 'ไม่ใช้งาน',
    'common.enabled': 'เปิดใช้งาน',
    'common.disabled': 'ปิดใช้งาน',
    'common.public': 'สาธารณะ',
    'common.private': 'ส่วนตัว',
    'common.draft': 'ร่าง',
    'common.published': 'เผยแพร่',
    'common.archived': 'เก็บถาวร',
    
    // Navigation
    'nav.dashboard': 'แดชบอร์ด',
    'nav.school_management': 'จัดการโรงเรียน',
    'nav.school_screenings': 'การตรวจสายตาโรงเรียน',
    'nav.students': 'นักเรียน',
    'nav.teachers': 'ครู',
    'nav.schools': 'โรงเรียน',
    'nav.parents': 'ผู้ปกครอง',
    'nav.medical_staff': 'บุคลากรทางการแพทย์',
    'nav.hospitals': 'โรงพยาบาล',
    'nav.screenings': 'การตรวจ',
    'nav.reports': 'รายงาน',
    'nav.settings': 'การตั้งค่า',
    'nav.user_management': 'จัดการผู้ใช้',
    'nav.admin_panel': 'แผงควบคุมผู้ดูแล',
    'nav.logout': 'ออกจากระบบ',
    'nav.profile': 'โปรไฟล์',
    'nav.notifications': 'การแจ้งเตือน',
    'nav.language': 'ภาษา',
    
    // School Screenings
    'school_screenings.title': 'การตรวจสายตาโรงเรียน',
    'school_screenings.subtitle': 'จัดการการตรวจสายตาของโรงเรียน',
    'school_screenings.create_new': 'สร้างการตรวจใหม่',
    'school_screenings.total_screenings': 'การตรวจทั้งหมด',
    'school_screenings.completed': 'เสร็จสิ้น',
    'school_screenings.in_progress': 'กำลังดำเนินการ',
    'school_screenings.pending': 'รอดำเนินการ',
    'school_screenings.available_students': 'นักเรียนที่พร้อมตรวจ',
    'school_screenings.recent_screenings': 'การตรวจล่าสุด',
    'school_screenings.show_filters': 'แสดงตัวกรอง',
    'school_screenings.student': 'นักเรียน',
    'school_screenings.examiner': 'ผู้ตรวจ',
    'school_screenings.type': 'ประเภท',
    'school_screenings.status': 'สถานะ',
    'school_screenings.date': 'วันที่',
    'school_screenings.actions': 'การดำเนินการ',
    'school_screenings.screenings': 'การตรวจ',
    'school_screenings.rescreen': 'ตรวจซ้ำ',
    'school_screenings.history': 'ประวัติ',
    'school_screenings.view_details': 'ดูรายละเอียด',
    'school_screenings.edit_screening': 'แก้ไขการตรวจ',
    'school_screenings.delete_screening': 'ลบการตรวจ',
    'school_screenings.print_screening': 'พิมพ์การตรวจ',
    'school_screenings.view_history': 'ดูประวัตินักเรียน',
    'school_screenings.basic_school': 'การตรวจพื้นฐานโรงเรียน',
    'school_screenings.vision_test': 'ทดสอบการมองเห็น',
    'school_screenings.comprehensive_vision': 'ทดสอบการมองเห็นแบบครอบคลุม',
    'school_screenings.color_blindness': 'ทดสอบตาบอดสี',
    'school_screenings.depth_perception': 'ทดสอบการรับรู้ความลึก',
    
    // Screening Form
    'screening_form.title': 'สร้างการตรวจสายตาโรงเรียนใหม่',
    'screening_form.student_selection': 'เลือกนักเรียน',
    'screening_form.screening_setup': 'ตั้งค่าการตรวจ',
    'screening_form.screening_results': 'ผลการตรวจ',
    'screening_form.conclusion': 'สรุป',
    'screening_form.select_student': 'เลือกนักเรียน',
    'screening_form.select_examiner': 'เลือกผู้ตรวจ',
    'screening_form.screening_type': 'ประเภทการตรวจ',
    'screening_form.screening_date': 'วันที่ตรวจ',
    'screening_form.notes': 'หมายเหตุ',
    'screening_form.left_eye': 'ตาซ้าย',
    'screening_form.right_eye': 'ตาขวา',
    'screening_form.distance_acuity': 'การมองเห็นระยะไกล',
    'screening_form.near_acuity': 'การมองเห็นระยะใกล้',
    'screening_form.color_vision': 'การมองเห็นสี',
    'screening_form.depth_perception': 'การรับรู้ความลึก',
    'screening_form.conclusion_text': 'สรุปผลการตรวจ',
    'screening_form.recommendations': 'ข้อแนะนำ',
    'screening_form.referral_needed': 'ต้องส่งต่อ',
    'screening_form.referral_notes': 'หมายเหตุการส่งต่อ',
    
    // Student Information
    'student.name': 'ชื่อนักเรียน',
    'student.grade_level': 'ระดับชั้น',
    'student.school': 'โรงเรียน',
    'student.birth_date': 'วันเกิด',
    'student.age': 'อายุ',
    'student.gender': 'เพศ',
    'student.parent_name': 'ชื่อผู้ปกครอง',
    'student.parent_phone': 'โทรศัพท์ผู้ปกครอง',
    'student.address': 'ที่อยู่',
    'student.male': 'ชาย',
    'student.female': 'หญิง',
    'student.years': 'ปี',
    
    // Teacher Information
    'teacher.name': 'ชื่อครู',
    'teacher.school': 'โรงเรียน',
    'teacher.email': 'อีเมล',
    'teacher.phone': 'โทรศัพท์',
    
    // Messages
    'message.screening_created': 'สร้างการตรวจสำเร็จ',
    'message.screening_updated': 'อัปเดตการตรวจสำเร็จ',
    'message.screening_deleted': 'ลบการตรวจสำเร็จ',
    'message.rescreen_created': 'สร้างการตรวจซ้ำสำเร็จ',
    'message.error_creating_screening': 'เกิดข้อผิดพลาดในการสร้างการตรวจ',
    'message.error_updating_screening': 'เกิดข้อผิดพลาดในการอัปเดตการตรวจ',
    'message.error_deleting_screening': 'เกิดข้อผิดพลาดในการลบการตรวจ',
    'message.error_fetching_data': 'เกิดข้อผิดพลาดในการดึงข้อมูล',
    'message.confirm_delete': 'คุณแน่ใจหรือไม่ว่าต้องการลบการตรวจนี้?',
    'message.confirm_rescreen': 'คุณแน่ใจหรือไม่ว่าต้องการสร้างการตรวจซ้ำสำหรับนักเรียนคนนี้?',
    'message.duplicate_screening': 'นักเรียนมีรายการตรวจในวันที่นี้แล้ว กรุณาใช้การตรวจซ้ำแทน',
    'message.print_dialog_opened': 'เปิดหน้าต่างพิมพ์สำเร็จ',
    'message.popup_blocked': 'กรุณาอนุญาตป๊อปอัพเพื่อพิมพ์รายงานการตรวจ',
    
    // Print Report
    'print.title': 'รายงานการตรวจสายตา',
    'print.student_info': 'ข้อมูลนักเรียน',
    'print.examiner_info': 'ข้อมูลผู้ตรวจ',
    'print.screening_results': 'ผลการตรวจ',
    'print.conclusion_recommendations': 'สรุปและข้อแนะนำ',
    'print.generated_by': 'รายงานนี้สร้างโดยระบบ EVEP',
    'print.printed_on': 'พิมพ์เมื่อ',
    'print.eye_left': 'ซ้าย',
    'print.eye_right': 'ขวา',
    'print.referral_yes': 'ใช่',
    'print.referral_no': 'ไม่',
    
    // Breadcrumbs
    'breadcrumb.dashboard': 'แดชบอร์ด',
    'breadcrumb.school_management': 'จัดการโรงเรียน',
    'breadcrumb.school_screenings': 'การตรวจสายตาโรงเรียน',
    
    // Filter Labels
    'filter.status': 'สถานะ',
    'filter.type': 'ประเภท',
    'filter.student': 'นักเรียน',
    'filter.examiner': 'ผู้ตรวจ',
    'filter.date_from': 'วันที่เริ่มต้น',
    'filter.date_to': 'วันที่สิ้นสุด',
    'filter.all_status': 'สถานะทั้งหมด',
    'filter.all_type': 'ประเภททั้งหมด',
    
    // Dialog Titles
    'dialog.create_screening': 'สร้างการตรวจสายตาโรงเรียนใหม่',
    'dialog.edit_screening': 'แก้ไขการตรวจสายตาโรงเรียน',
    'dialog.view_screening': 'ดูรายละเอียดการตรวจ',
    'dialog.student_history': 'ประวัติการตรวจของนักเรียน',
    'dialog.confirm_delete': 'ยืนยันการลบ',
    'dialog.confirm_rescreen': 'ยืนยันการตรวจซ้ำ',
    
    // Form Steps
    'step.student_selection': 'เลือกนักเรียน',
    'step.screening_setup': 'ตั้งค่าการตรวจ',
    'step.screening_results': 'ผลการตรวจ',
    'step.conclusion': 'สรุป',
    
    // Form Labels
    'form.select_student': 'เลือกนักเรียน',
    'form.select_examiner': 'เลือกผู้ตรวจ',
    'form.screening_type': 'ประเภทการตรวจ',
    'form.screening_date': 'วันที่ตรวจ',
    'form.notes': 'หมายเหตุ',
    'form.left_eye': 'ตาซ้าย',
    'form.right_eye': 'ตาขวา',
    'form.distance_acuity': 'การมองเห็นระยะไกล',
    'form.near_acuity': 'การมองเห็นระยะใกล้',
    'form.color_vision': 'การมองเห็นสี',
    'form.depth_perception': 'การรับรู้ความลึก',
    'form.conclusion': 'สรุป',
    'form.recommendations': 'ข้อแนะนำ',
    'form.referral_needed': 'ต้องส่งต่อ',
    'form.referral_notes': 'หมายเหตุการส่งต่อ',
    
    // Action Buttons
    'action.view': 'ดู',
    'action.edit': 'แก้ไข',
    'action.delete': 'ลบ',
    'action.print': 'พิมพ์',
    'action.rescreen': 'ตรวจซ้ำ',
    'action.history': 'ประวัติ',
    'action.save': 'บันทึก',
    'action.cancel': 'ยกเลิก',
    'action.close': 'ปิด',
    'action.next': 'ถัดไป',
    'action.previous': 'ก่อนหน้า',
    'action.finish': 'เสร็จสิ้น',
    
    // Status Messages
    'status.loading': 'กำลังโหลด...',
    'status.success': 'สำเร็จ',
    'status.error': 'ข้อผิดพลาด',
    'status.warning': 'คำเตือน',
    'status.info': 'ข้อมูล',
    
    // Validation Messages
    'validation.required': 'ฟิลด์นี้จำเป็นต้องกรอก',
    'validation.invalid_email': 'กรุณากรอกอีเมลที่ถูกต้อง',
    'validation.invalid_phone': 'กรุณากรอกเบอร์โทรศัพท์ที่ถูกต้อง',
    'validation.invalid_date': 'กรุณากรอกวันที่ที่ถูกต้อง',
    'validation.min_length': 'ความยาวขั้นต่ำ {{min}} ตัวอักษร',
    'validation.max_length': 'ความยาวสูงสุด {{max}} ตัวอักษร',
    'validation.email_required': 'ต้องกรอกอีเมล',
    'validation.email_invalid': 'กรุณากรอกอีเมลที่ถูกต้อง',
    'validation.password_required': 'ต้องกรอกรหัสผ่าน',
    'validation.password_min_length': 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
    
    // Time and Date
    'time.today': 'วันนี้',
    'time.yesterday': 'เมื่อวาน',
    'time.tomorrow': 'พรุ่งนี้',
    'time.now': 'ตอนนี้',
    'time.ago': 'ที่แล้ว',
    'time.in': 'ใน',
    
    // Pagination
    'pagination.page': 'หน้า',
    'pagination.of': 'จาก',
    'pagination.rows_per_page': 'แถวต่อหน้า',
    'pagination.showing': 'แสดง',
    'pagination.to': 'ถึง',
    'pagination.of_total': 'จากทั้งหมด {{total}}',
    
    // Search and Sort
    'search.placeholder': 'ค้นหา...',
    'search.no_results': 'ไม่พบผลลัพธ์',
    'search.clear': 'ล้างการค้นหา',
    'sort.asc': 'เรียงจากน้อยไปมาก',
    'sort.desc': 'เรียงจากมากไปน้อย',
    'sort.by': 'เรียงตาม',
    
    // Dashboard
    'dashboard.title': 'แดชบอร์ด',
    'dashboard.subtitle': 'ภาพรวมพอร์ทัลการแพทย์',
    'dashboard.total_patients': 'ผู้ป่วยทั้งหมด',
    'dashboard.total_screenings': 'การตรวจทั้งหมด',
    'dashboard.pending_screenings': 'การตรวจที่รอดำเนินการ',
    'dashboard.completed_screenings': 'การตรวจที่เสร็จสิ้น',
    'dashboard.today_appointments': 'นัดหมายวันนี้',
    'dashboard.recent_activities': 'กิจกรรมล่าสุด',
    'dashboard.quick_actions': 'การดำเนินการด่วน',
    'dashboard.statistics': 'สถิติ',
    'dashboard.overview': 'ภาพรวม',
    
    // Patients
    'patients.title': 'ผู้ป่วย',
    'patients.subtitle': 'จัดการผู้ป่วย',
    'patients.add_patient': 'เพิ่มผู้ป่วย',
    'patients.search_patients': 'ค้นหาผู้ป่วย',
    'patients.filter_by_status': 'กรองตามสถานะ',
    'patients.filter_by_gender': 'กรองตามเพศ',
    'patients.all_status': 'สถานะทั้งหมด',
    'patients.all_gender': 'เพศทั้งหมด',
    'patients.active': 'ใช้งานอยู่',
    'patients.inactive': 'ไม่ใช้งาน',
    'patients.male': 'ชาย',
    'patients.female': 'หญิง',
    'patients.patient_details': 'รายละเอียดผู้ป่วย',
    'patients.edit_patient': 'แก้ไขผู้ป่วย',
    'patients.delete_patient': 'ลบผู้ป่วย',
    'patients.view_patient': 'ดูผู้ป่วย',
    'patients.patient_id': 'รหัสผู้ป่วย',
    'patients.full_name': 'ชื่อเต็ม',
    'patients.date_of_birth': 'วันเกิด',
    'patients.gender': 'เพศ',
    'patients.phone': 'โทรศัพท์',
    'patients.email': 'อีเมล',
    'patients.address': 'ที่อยู่',
    'patients.emergency_contact': 'ผู้ติดต่อฉุกเฉิน',
    'patients.medical_history': 'ประวัติการรักษา',
    'patients.insurance_info': 'ข้อมูลประกัน',
    'patients.appointment': 'ผู้ป่วยนัดหมาย',
    'patients.manual_registration': 'การลงทะเบียนด้วยตนเอง',
    
    // Screenings
    'screenings.title': 'การตรวจ',
    'screenings.subtitle': 'จัดการการตรวจสายตา',
    'screenings.create_session': 'สร้างเซสชันการตรวจ',
    'screenings.active_sessions': 'เซสชันที่ใช้งานอยู่',
    'screenings.completed_sessions': 'เซสชันที่เสร็จสิ้น',
    'screenings.screening_type': 'ประเภทการตรวจ',
    'screenings.basic_screening': 'การตรวจพื้นฐาน',
    'screenings.comprehensive_screening': 'การตรวจแบบครอบคลุม',
    'screenings.mobile_screening': 'การตรวจเคลื่อนที่',
    'screenings.standard_screening': 'การตรวจมาตรฐาน',
    'screenings.session_details': 'รายละเอียดเซสชัน',
    'screenings.start_screening': 'เริ่มการตรวจ',
    'screenings.complete_screening': 'เสร็จสิ้นการตรวจ',
    'screenings.screening_results': 'ผลการตรวจ',
    'screenings.left_eye': 'ตาซ้าย',
    'screenings.right_eye': 'ตาขวา',
    'screenings.distance_vision': 'การมองเห็นระยะไกล',
    'screenings.near_vision': 'การมองเห็นระยะใกล้',
    'screenings.color_vision': 'การมองเห็นสี',
    'screenings.depth_perception': 'การรับรู้ความลึก',
    'screenings.notes': 'หมายเหตุ',
    'screenings.recommendations': 'ข้อแนะนำ',
    'screenings.follow_up_required': 'ต้องติดตามผล',
    'screenings.all_screenings': 'การตรวจทั้งหมด',
    
    // Reports
    'reports.title': 'รายงาน',
    'reports.subtitle': 'รายงานและการวิเคราะห์ทางการแพทย์',
    'reports.generate_report': 'สร้างรายงาน',
    'reports.screening_reports': 'รายงานการตรวจ',
    'reports.patient_reports': 'รายงานผู้ป่วย',
    'reports.statistical_reports': 'รายงานสถิติ',
    'reports.date_range': 'ช่วงวันที่',
    'reports.from_date': 'จากวันที่',
    'reports.to_date': 'ถึงวันที่',
    'reports.report_type': 'ประเภทรายงาน',
    'reports.export_format': 'รูปแบบการส่งออก',
    'reports.pdf': 'PDF',
    'reports.excel': 'Excel',
    'reports.csv': 'CSV',
    'reports.download_report': 'ดาวน์โหลดรายงาน',
    'reports.view_report': 'ดูรายงาน',
    'reports.medical_reports': 'รายงานทางการแพทย์',
    'reports.evep_medical_panel': 'แผงควบคุมผู้เชี่ยวชาญทางการแพทย์ EVEP',
    
    // EVEP Students
    'evep_students.title': 'นักเรียน EVEP',
    'evep_students.subtitle': 'จัดการนักเรียน',
    'evep_students.add_student': 'เพิ่มนักเรียน',
    'evep_students.student_code': 'รหัสนักเรียน',
    'evep_students.school_name': 'ชื่อโรงเรียน',
    'evep_students.grade_level': 'ระดับชั้น',
    'evep_students.grade_number': 'เลขชั้น',
    'evep_students.parent_name': 'ชื่อผู้ปกครอง',
    'evep_students.consent_status': 'สถานะการยินยอม',
    'evep_students.consent_given': 'ให้ยินยอมแล้ว',
    'evep_students.consent_pending': 'รอยินยอม',
    'evep_students.consent_denied': 'ปฏิเสธการยินยอม',
    'evep_students.filter_by_school': 'กรองตามโรงเรียน',
    'evep_students.filter_by_grade': 'กรองตามชั้น',
    'evep_students.filter_by_consent': 'กรองตามการยินยอม',
    'evep_students.all_schools': 'โรงเรียนทั้งหมด',
    'evep_students.all_grades': 'ชั้นทั้งหมด',
    'evep_students.all_consent': 'สถานะการยินยอมทั้งหมด',
    'evep_students.total_students': 'นักเรียนทั้งหมด',
    'evep_students.male_students': 'นักเรียนชาย',
    'evep_students.female_students': 'นักเรียนหญิง',
    'evep_students.students_list': 'รายชื่อนักเรียน',
    
    // EVEP Parents
    'evep_parents.title': 'ผู้ปกครอง EVEP',
    'evep_parents.subtitle': 'จัดการผู้ปกครอง',
    'evep_parents.add_parent': 'เพิ่มผู้ปกครอง',
    'evep_parents.parent_id': 'รหัสผู้ปกครอง',
    'evep_parents.relationship': 'ความสัมพันธ์',
    'evep_parents.father': 'บิดา',
    'evep_parents.mother': 'มารดา',
    'evep_parents.guardian': 'ผู้ปกครอง',
    'evep_parents.occupation': 'อาชีพ',
    'evep_parents.workplace': 'สถานที่ทำงาน',
    'evep_parents.children': 'บุตร',
    'evep_parents.emergency_contact': 'ผู้ติดต่อฉุกเฉิน',
    'evep_parents.total_parents': 'ผู้ปกครองทั้งหมด',
    'evep_parents.parents_list': 'รายชื่อผู้ปกครอง',
    
    // EVEP Teachers
    'evep_teachers.title': 'ครู EVEP',
    'evep_teachers.subtitle': 'จัดการครู',
    'evep_teachers.add_teacher': 'เพิ่มครู',
    'evep_teachers.teacher_id': 'รหัสครู',
    'evep_teachers.position': 'ตำแหน่ง',
    'evep_teachers.subject': 'วิชา',
    'evep_teachers.experience_years': 'ประสบการณ์ (ปี)',
    'evep_teachers.qualification': 'คุณวุฒิ',
    'evep_teachers.classes': 'ชั้นเรียน',
    'evep_teachers.students_count': 'จำนวนนักเรียน',
    'evep_teachers.total_teachers': 'ครูทั้งหมด',
    'evep_teachers.male_teachers': 'ครูชาย',
    'evep_teachers.female_teachers': 'ครูหญิง',
    'evep_teachers.teachers_list': 'รายชื่อครู',
    
    // EVEP Schools
    'evep_schools.title': 'โรงเรียน EVEP',
    'evep_schools.subtitle': 'จัดการโรงเรียน',
    'evep_schools.add_school': 'เพิ่มโรงเรียน',
    'evep_schools.school_id': 'รหัสโรงเรียน',
    'evep_schools.school_type': 'ประเภทโรงเรียน',
    'evep_schools.public_school': 'โรงเรียนรัฐ',
    'evep_schools.private_school': 'โรงเรียนเอกชน',
    'evep_schools.school_level': 'ระดับโรงเรียน',
    'evep_schools.elementary': 'ประถมศึกษา',
    'evep_schools.secondary': 'มัธยมศึกษาตอนต้น',
    'evep_schools.high_school': 'มัธยมศึกษาตอนปลาย',
    'evep_schools.principal_name': 'ชื่อผู้อำนวยการ',
    'evep_schools.total_students': 'นักเรียนทั้งหมด',
    'evep_schools.total_teachers': 'ครูทั้งหมด',
    'evep_schools.contact_person': 'ผู้ติดต่อ',
    'evep_schools.contact_phone': 'เบอร์โทรติดต่อ',
    'evep_schools.contact_email': 'อีเมลติดต่อ',
    
    // Admin Management
    'admin.title': 'แผงควบคุมผู้ดูแลระบบ',
    'admin.subtitle': 'การจัดการระบบ',
    'admin.user_management': 'จัดการผู้ใช้',
    'admin.role_management': 'จัดการบทบาท',
    'admin.permission_management': 'จัดการสิทธิ์',
    'admin.system_settings': 'การตั้งค่าระบบ',
    'admin.dashboard_title': 'แดชบอร์ดผู้ดูแลระบบ',
    'admin.dashboard_subtitle': 'ภาพรวมและการจัดการระบบ',
    'admin.total_users': 'ผู้ใช้ทั้งหมด',
    'admin.total_patients': 'ผู้ป่วยทั้งหมด',
    'admin.total_screenings': 'การคัดกรองทั้งหมด',
    'admin.security_settings': 'การตั้งค่าความปลอดภัย',
    'admin.audit_logs': 'บันทึกการตรวจสอบ',
    'admin.system_monitoring': 'การตรวจสอบระบบ',
    'admin.backup_restore': 'สำรองและกู้คืน',
    'admin.database_management': 'จัดการฐานข้อมูล',
    'admin.api_management': 'จัดการ API',
    
    // User Management
    'user_management.title': 'จัดการผู้ใช้',
    'user_management.subtitle': 'จัดการผู้ใช้ระบบ',
    'user_management.add_user': 'เพิ่มผู้ใช้',
    'user_management.user_id': 'รหัสผู้ใช้',
    'user_management.username': 'ชื่อผู้ใช้',
    'user_management.full_name': 'ชื่อเต็ม',
    'user_management.role': 'บทบาท',
    'user_management.department': 'แผนก',
    'user_management.status': 'สถานะ',
    'user_management.last_login': 'เข้าสู่ระบบล่าสุด',
    'user_management.created_at': 'สร้างเมื่อ',
    'user_management.updated_at': 'อัปเดตเมื่อ',
    'user_management.active': 'ใช้งานอยู่',
    'user_management.inactive': 'ไม่ใช้งาน',
    'user_management.suspended': 'ระงับการใช้งาน',
    'user_management.reset_password': 'รีเซ็ตรหัสผ่าน',
    'user_management.change_role': 'เปลี่ยนบทบาท',
    'user_management.activate_user': 'เปิดใช้งานผู้ใช้',
    'user_management.deactivate_user': 'ปิดใช้งานผู้ใช้',
    'user_management.total_users': 'ผู้ใช้ทั้งหมด',
    'user_management.active_users': 'ผู้ใช้ที่ใช้งานอยู่',
    'user_management.inactive_users': 'ผู้ใช้ที่ไม่ใช้งาน',
    'user_management.search_users': 'ค้นหาผู้ใช้...',
    
    // RBAC Management
    'rbac.title': 'การควบคุมการเข้าถึงตามบทบาท',
    'rbac.subtitle': 'จัดการบทบาทและสิทธิ์',
    'rbac.create_role': 'สร้างบทบาท',
    'rbac.edit_role': 'แก้ไขบทบาท',
    'rbac.delete_role': 'ลบบทบาท',
    'rbac.role_name': 'ชื่อบทบาท',
    'rbac.role_description': 'คำอธิบายบทบาท',
    'rbac.permissions': 'สิทธิ์',
    'rbac.roles': 'บทบาท',
    'rbac.user_roles': 'บทบาทผู้ใช้',
    'rbac.master_data': 'ข้อมูลหลัก',
    'rbac.screening_rbac': 'การคัดกรอง RBAC',
    'rbac.assign_permissions': 'กำหนดสิทธิ์',
    'rbac.users_with_role': 'ผู้ใช้ที่มีบทบาทนี้',
    'rbac.permission_categories': 'หมวดหมู่สิทธิ์',
    'rbac.read': 'อ่าน',
    'rbac.write': 'เขียน',
    'rbac.delete': 'ลบ',
    'rbac.admin': 'ผู้ดูแลระบบ',
    'rbac.user': 'ผู้ใช้',
    'rbac.guest': 'ผู้เยี่ยมชม',
    
    // Medical Staff
    'medical_staff.title': 'บุคลากรทางการแพทย์',
    'medical_staff.subtitle': 'จัดการบุคลากรทางการแพทย์',
    'medical_staff.add_staff': 'เพิ่มบุคลากร',
    'medical_staff.staff_id': 'รหัสบุคลากร',
    'medical_staff.license_number': 'หมายเลขใบอนุญาต',
    'medical_staff.specialization': 'ความเชี่ยวชาญ',
    'medical_staff.experience': 'ประสบการณ์',
    'medical_staff.certification': 'ใบรับรอง',
    'medical_staff.availability': 'ความพร้อมใช้งาน',
    'medical_staff.schedule': 'ตารางงาน',
    'medical_staff.patients_assigned': 'ผู้ป่วยที่ได้รับมอบหมาย',
    'medical_staff.screenings_performed': 'การตรวจที่ดำเนินการ',
    
    // Hospitals Management
    'hospitals.title': 'โรงพยาบาล',
    'hospitals.subtitle': 'จัดการโรงพยาบาล',
    'hospitals.add_hospital': 'เพิ่มโรงพยาบาล',
    'hospitals.hospital_id': 'รหัสโรงพยาบาล',
    'hospitals.hospital_name': 'ชื่อโรงพยาบาล',
    'hospitals.hospital_type': 'ประเภทโรงพยาบาล',
    'hospitals.general_hospital': 'โรงพยาบาลทั่วไป',
    'hospitals.specialty_hospital': 'โรงพยาบาลเฉพาะทาง',
    'hospitals.clinic': 'คลินิก',
    'hospitals.medical_center': 'ศูนย์การแพทย์',
    'hospitals.capacity': 'ความจุ',
    'hospitals.beds_available': 'เตียงว่าง',
    'hospitals.emergency_services': 'บริการฉุกเฉิน',
    'hospitals.specialties': 'ความเชี่ยวชาญเฉพาะ',
    'hospitals.contact_info': 'ข้อมูลติดต่อ',
    
    // Settings
    'settings.title': 'การตั้งค่า',
    'settings.subtitle': 'การกำหนดค่าระบบ',
    'settings.general_settings': 'การตั้งค่าทั่วไป',
    'settings.display_settings': 'การตั้งค่าการแสดงผล',
    'settings.notification_settings': 'การตั้งค่าการแจ้งเตือน',
    'settings.security_settings': 'การตั้งค่าความปลอดภัย',
    'settings.medical_settings': 'การตั้งค่าทางการแพทย์',
    'settings.panel_name': 'ชื่อแผงควบคุม',
    'settings.panel_description': 'คำอธิบายแผงควบคุม',
    'settings.timezone': 'เขตเวลา',
    'settings.date_format': 'รูปแบบวันที่',
    'settings.time_format': 'รูปแบบเวลา',
    'settings.language': 'ภาษา',
    'settings.theme': 'ธีม',
    'settings.light_theme': 'ธีมสว่าง',
    'settings.dark_theme': 'ธีมมืด',
    'settings.auto_theme': 'ธีมอัตโนมัติ',
    'settings.compact_mode': 'โหมดกะทัดรัด',
    'settings.show_animations': 'แสดงแอนิเมชัน',
    'settings.auto_refresh': 'รีเฟรชอัตโนมัติ',
    'settings.refresh_interval': 'ช่วงเวลาการรีเฟรช',
    'settings.email_notifications': 'การแจ้งเตือนทางอีเมล',
    'settings.push_notifications': 'การแจ้งเตือนแบบพุช',
    'settings.screening_alerts': 'การแจ้งเตือนการตรวจ',
    'settings.appointment_reminders': 'การแจ้งเตือนนัดหมาย',
    'settings.system_updates': 'การอัปเดตระบบ',
    'settings.session_timeout': 'หมดเวลาการเข้าสู่ระบบ',
    'settings.require_password_change': 'ต้องเปลี่ยนรหัสผ่าน',
    'settings.two_factor_auth': 'การยืนยันตัวตนสองขั้นตอน',
    'settings.audit_logging': 'การบันทึกการตรวจสอบ',
    'settings.default_screening_type': 'ประเภทการตรวจเริ่มต้น',
    'settings.auto_save_screening_data': 'บันทึกข้อมูลการตรวจอัตโนมัติ',
    'settings.patient_data_retention': 'การเก็บรักษาข้อมูลผู้ป่วย',
    'settings.medical_alerts': 'การแจ้งเตือนทางการแพทย์',
    
    // AI Insights
    'ai_insights.title': 'ข้อมูลเชิงลึก AI',
    'ai_insights.subtitle': 'การวิเคราะห์ปัญญาประดิษฐ์',
    'ai_insights.dashboard': 'แดชบอร์ด AI',
    'ai_insights.predictive_analytics': 'การวิเคราะห์เชิงทำนาย',
    'ai_insights.pattern_recognition': 'การจดจำรูปแบบ',
    'ai_insights.recommendations': 'คำแนะนำ AI',
    'ai_insights.risk_assessment': 'การประเมินความเสี่ยง',
    'ai_insights.trend_analysis': 'การวิเคราะห์แนวโน้ม',
    'ai_insights.anomaly_detection': 'การตรวจจับความผิดปกติ',
    'ai_insights.performance_metrics': 'ตัวชี้วัดประสิทธิภาพ',
    'ai_insights.data_quality': 'คุณภาพข้อมูล',
    'ai_insights.insights_generated': 'ข้อมูลเชิงลึกที่สร้างขึ้น',
    'ai_insights.confidence_score': 'คะแนนความเชื่อมั่น',
    'ai_insights.recommendation_engine': 'เครื่องมือแนะนำ',
    'ai_insights.no_permission': 'คุณไม่มีสิทธิ์เข้าถึงข้อมูลเชิงลึก AI',
    
    // Authentication
    'auth.login': 'เข้าสู่ระบบ',
    'auth.register': 'สมัครสมาชิก',
    'auth.logout': 'ออกจากระบบ',
    'auth.forgot_password': 'ลืมรหัสผ่าน',
    'auth.reset_password': 'รีเซ็ตรหัสผ่าน',
    'auth.change_password': 'เปลี่ยนรหัสผ่าน',
    'auth.email': 'อีเมล',
    'auth.password': 'รหัสผ่าน',
    'auth.confirm_password': 'ยืนยันรหัสผ่าน',
    'auth.new_password': 'รหัสผ่านใหม่',
    'auth.current_password': 'รหัสผ่านปัจจุบัน',
    'auth.remember_me': 'จดจำฉัน',
    'auth.login_button': 'เข้าสู่ระบบ',
    'auth.register_button': 'สมัครสมาชิก',
    'auth.login_title': 'ยินดีต้อนรับกลับ',
    'auth.register_title': 'สร้างบัญชี',
    'auth.login_subtitle': 'เข้าสู่ระบบบัญชีของคุณ',
    'auth.register_subtitle': 'สร้างบัญชีใหม่',
    'auth.switch_to_login': 'มีบัญชีแล้ว? เข้าสู่ระบบ',
    'auth.switch_to_register': 'ไม่มีบัญชี? สมัครสมาชิก',
    'auth.login_success': 'เข้าสู่ระบบสำเร็จ',
    'auth.login_error': 'เข้าสู่ระบบล้มเหลว',
    'auth.register_success': 'สมัครสมาชิกสำเร็จ',
    'auth.register_error': 'สมัครสมาชิกล้มเหลว',
    'auth.password_reset_sent': 'ส่งอีเมลรีเซ็ตรหัสผ่านแล้ว',
    'auth.password_reset_error': 'รีเซ็ตรหัสผ่านล้มเหลว',
    'auth.invalid_credentials': 'อีเมลหรือรหัสผ่านไม่ถูกต้อง',
    'auth.account_locked': 'บัญชีถูกล็อค',
    'auth.account_disabled': 'บัญชีถูกปิดใช้งาน',
    'auth.email_required': 'ต้องกรอกอีเมล',
    'auth.password_required': 'ต้องกรอกรหัสผ่าน',
    'auth.password_too_short': 'รหัสผ่านต้องมีอย่างน้อย 8 ตัวอักษร',
    'auth.password_mismatch': 'รหัสผ่านไม่ตรงกัน',
    'auth.email_invalid': 'กรุณากรอกอีเมลที่ถูกต้อง',
    'auth.sign_in': 'เข้าสู่ระบบ',
    'auth.access_dashboard': 'เข้าถึงแดชบอร์ดผู้เชี่ยวชาญทางการแพทย์',
    'auth.demo_access': 'การเข้าถึงแบบทดลอง',
    'auth.demo_description': 'ลองใช้แพลตฟอร์มด้วยข้อมูลทดลอง',
    'auth.welcome_message': 'ยินดีต้อนรับสู่แผงควบคุมผู้เชี่ยวชาญทางการแพทย์ EVEP',
    'auth.demo_welcome': 'ยินดีต้อนรับ, {{role}}!',
    'auth.login_failed': 'เข้าสู่ระบบล้มเหลว',
    
    // Master Data Management
    'master_data.title': 'ข้อมูลหลัก',
    'master_data.subtitle': 'จัดการข้อมูลหลักของระบบ',
    'master_data.provinces': 'จังหวัด',
    'master_data.districts': 'อำเภอ',
    'master_data.subdistricts': 'ตำบล',
    'master_data.schools': 'โรงเรียน',
    'master_data.grades': 'ชั้นเรียน',
    'master_data.subjects': 'วิชา',
    'master_data.diseases': 'โรค',
    'master_data.medications': 'ยา',
    'master_data.treatments': 'การรักษา',
    'master_data.add_province': 'เพิ่มจังหวัด',
    'master_data.add_district': 'เพิ่มอำเภอ',
    'master_data.add_subdistrict': 'เพิ่มตำบล',
    'master_data.add_school': 'เพิ่มโรงเรียน',
    'master_data.add_grade': 'เพิ่มชั้นเรียน',
    'master_data.add_subject': 'เพิ่มวิชา',
    'master_data.add_disease': 'เพิ่มโรค',
    'master_data.add_medication': 'เพิ่มยา',
    'master_data.add_treatment': 'เพิ่มการรักษา',
    
    // Geolocations Management
    'geolocations.title': 'ตำแหน่งทางภูมิศาสตร์',
    'geolocations.subtitle': 'จัดการตำแหน่งทางภูมิศาสตร์',
    'geolocations.latitude': 'ละติจูด',
    'geolocations.longitude': 'ลองจิจูด',
    'geolocations.address': 'ที่อยู่',
    'geolocations.postal_code': 'รหัสไปรษณีย์',
    'geolocations.map_view': 'มุมมองแผนที่',
    'geolocations.location_details': 'รายละเอียดตำแหน่ง',
    'geolocations.add_location': 'เพิ่มตำแหน่ง',
    'geolocations.edit_location': 'แก้ไขตำแหน่ง',
    'geolocations.delete_location': 'ลบตำแหน่ง',
    'geolocations.search_location': 'ค้นหาตำแหน่ง',
    'geolocations.nearby_locations': 'ตำแหน่งใกล้เคียง',
    'geolocations.distance': 'ระยะทาง',
    'geolocations.direction': 'ทิศทาง',
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = (translations[language] as any)[key] || key;
    
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translation = translation.replace(`{{${paramKey}}}`, String(paramValue));
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
